// Generated by IcedCoffeeScript 108.0.9
(function() {
  requirejs.config({
    paths: {
      jquery: 'Libraries/jquery',
      ajax: 'Libraries/ajax'
    }
  });

  requirejs(['website']);

}).call(this);
