// Generated by IcedCoffeeScript 108.0.9
(function() {
  requirejs.config({
    paths: {
      jquery: 'Libraries/jquery',
      jcookie: 'Libraries/jcookie',
      ajax: 'Libraries/ajax',
      cookies: 'Libraries/cookies'
    }
  });

  requirejs(['website']);

}).call(this);
