// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(['jquery', 'ajax'], function($, ajax) {
    var website;
    website = {
      choicesSectionSelector: 'section.choices',
      choicesFormSelector: 'section.choices form',
      initialize: function() {
        return ajax.setupLiveForm(website.choicesFormSelector, website.handleAjax, website.handleAjaxError);
      },
      handleChoiceResponse: function(response) {
        var newChoicesSection;
        newChoicesSection = $(response).find(website.choicesSectionSelector);
        return $(website.choicesSectionSelector).replaceWith(newChoicesSection);
      },
      handleAjaxError: function() {
        return alert('Ajax error');
      }
    };
    return website;
  });

}).call(this);
