// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(['ajax', 'xhr'], function(ajax, xhr) {
    var website, _xhr;
    _xhr = xhr;
    website = {
      choicesSectionSelector: 'section.choices',
      choicesFormSelector: 'section.choices form',
      handleChoiceResponse: function(response) {
        var newChoices, newChoicesSection, newUrl;
        newUrl = _xhr.fromLastCall.responseURL;
        history.replaceState({}, '', newUrl);
        newChoicesSection = $(response).find(website.choicesSectionSelector);
        $(website.choicesSectionSelector).replaceWith(newChoicesSection);
        newChoices = $(website.choicesFormSelector);
        newChoices.hide();
        return newChoices.fadeIn(200);
      },
      handleAjaxError: function() {
        return alert('Ajax error');
      }
    };
    ajax.setupLiveForm(website.choicesFormSelector, website.handleChoiceResponse, website.handleAjaxError);
    return website;
  });

}).call(this);
