// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(['jquery'], function($) {
    var xhr;
    xhr = {
      originalXhr: $.ajaxSettings.xhr,
      fromLastCall: null
    };
    $.ajaxSettings.xhr = function() {
      return xhr.fromLastCall = xhr.originalXhr();
    };
    return xhr;
  });

}).call(this);