// Generated by IcedCoffeeScript 108.0.9
(function() {
  define([], function($) {
    var cookies;
    cookies = {
      get: function(name) {
        var cookieString, endIndex, startIndex;
        cookieString = document.cookie + ";";
        startIndex = cookieString.indexOf(name + "=");
        endIndex = cookieString.indexOf(";", startIndex);
        if (startIndex === -1) {
          return null;
        } else {
          return cookieString.substring(startIndex, endIndex);
        }
      }
    };
    return cookies;
  });

}).call(this);
