CREATE TABLE dbo.[Event]
(
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Name NVARCHAR(128) NOT NULL,
  [Text] NVARCHAR(1024) NOT NULL,
  [Automatic] BIT NOT NULL,
  OneTime BIT NOT NULL,
  Steps BIT NOT NULL,
)
