CREATE TABLE dbo.UserSession
(
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  CreateDate DATETIME NOT NULL,
  TempToken NVARCHAR(1024) NOT NULL,
  TempSecret NVARCHAR(1024) NOT NULL,
  Verifier NVARCHAR(1024) NULL,
  Token NVARCHAR(1024) NULL,
  [Secret] NVARCHAR(1024) NULL,
  UserId NVARCHAR(1024) NULL,
  OffsetFromUtcMillis INT NULL,
)
